name: Build and Test

on: [push, pull_request]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean test jacoco:report -Plocal

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/  # Для Maven (Gradle: build/reports/jacoco/test)
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
      - name: Update badge in README
        run: |
          COVERAGE=${{ steps.jacoco.outputs.coverage }}
          COVERAGE_PERCENT=$(echo "$COVERAGE * 100" | bc | awk '{printf "%.0f", $1}')
          echo "Formatted coverage: ${COVERAGE_PERCENT}%"
          sed -i "s/coverage-[0-9]\+%25/coverage-${COVERAGE_PERCENT}%25/g" README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update coverage badge to ${COVERAGE_PERCENT}%"
          git push
        env:
          COVERAGE: ${{ steps.coverage.outputs.coverage }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}